### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by taylorsargent** [taylorsargent/dsn1675-assignment-1#1]
Finished coding my website and the URL link does not work! Is there something I am missing

@thomasjbradley

**Comment by thomasjbradley** [comment]
GitHub can't find your index.html because of how the folders are organized: the assets, content, design & prod folders shouldn't be on GitHub.

Then the index, images and CSS should move out of the folder they are inside.

**Comment by taylorsargent** [comment]
I re-arranged the folders but it is still not recognizing the index.html? This is how I have them set up
![screen shot 2015-09-16 at 6 27 25 pm](https://cloud.githubusercontent.com/assets/10464306/9920265/a1fff070-5ca0-11e5-9caa-c423972e5103.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
They are still all up on GitHub; did you sync?

**Comment by taylorsargent** [comment]
I have synced it a couple times and it is still not taking them down... If I can not figure it out before Friday, am I able to come in early to get your help? @thomasjbradley

**Comment by thomasjbradley** [comment]
Yeah, we can look at it before class.
